import { useEffect, useState } from 'react';
import { Link } from 'expo-router';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { useTranslation } from 'react-i18next';
import { ReadModelStatus } from '@/components/ReadModelStatus';
import { hasFreshMutationAuthorization } from '@/domain/mutationAuthorization';
import { LocalStore } from '@/offline/localStore';
import { cacheOrganizationSettings, getCachedOrganizationSettings, isSnapshotStale, OPERATIONAL_READ_MODEL_MAX_AGE_MS } from '@/offline/readModels';
import { useAuth } from '@/providers/AuthProvider';
import { useConnectivity } from '@/providers/ConnectivityProvider';
import { useOrganization } from '@/providers/OrganizationProvider';
import { commitImportJob, loadAuditLogs, loadImportJobs, loadNotificationPreferences, loadNotifications, loadOrganizationSettings, loadSubscription, markNotificationRead, parseCsv, saveNotificationPreferences, saveOrganizationSettings, stageImport, type AuditLog, type ImportJob, type Notification, type NotificationPreferences, type OrganizationSettings, type SubscriptionPlan, type Subscription } from '@/services/coreCompletion';

const importTypes:ImportJob['import_type'][]=['PRODUCTS','SUPPLIERS','CUSTOMERS','OPENING_STOCK'];
const localStore=new LocalStore();
export default function OperationsScreen(){
 const{t}=useTranslation();const{user}=useAuth();const{organization,branch,can,usingCachedData,contextSyncedAt}=useOrganization();
 const{isOnline}=useConnectivity();
 const[notifications,setNotifications]=useState<Notification[]>([]);const[prefs,setPrefs]=useState<NotificationPreferences|null>(null);const[settings,setSettings]=useState<OrganizationSettings|null>(null);const[settingsLoading,setSettingsLoading]=useState(true);const[settingsSyncedAt,setSettingsSyncedAt]=useState<string|null>(null);const[settingsCached,setSettingsCached]=useState(false);const[subscription,setSubscription]=useState<Subscription|null>(null);const[plan,setPlan]=useState<SubscriptionPlan|null>(null);const[audit,setAudit]=useState<AuditLog[]>([]);const[jobs,setJobs]=useState<ImportJob[]>([]);const[receiptFooter,setReceiptFooter]=useState('');const[lowStock,setLowStock]=useState('5');const[defaultPayment,setDefaultPayment]=useState<OrganizationSettings['default_payment_method']>('CASH');const[importType,setImportType]=useState<ImportJob['import_type']>('PRODUCTS');const[fileName,setFileName]=useState('import.csv');const[csv,setCsv]=useState('');const[error,setError]=useState<string|null>(null);const[message,setMessage]=useState<string|null>(null);const[busy,setBusy]=useState(false);
 const canSettings=can('settings.manage'),canImport=can('import.manage'),canAudit=can('audit.read'),canNotifications=can('notification.read'),canSub=can('subscription.read');
 const mutationsAllowed=hasFreshMutationAuthorization(isOnline,usingCachedData,contextSyncedAt);
 const applySettings=(v:OrganizationSettings|null)=>{setSettings(v);if(v){setReceiptFooter(v.receipt_footer??'');setLowStock(String(v.low_stock_default_threshold));setDefaultPayment(v.default_payment_method);}};
 const refresh=async()=>{if(!organization||!user)return;setSettingsLoading(true);const cached=getCachedOrganizationSettings(localStore,organization.id);if(cached){applySettings(cached.data);setSettingsSyncedAt(cached.syncedAt);setSettingsCached(true);}if(!isOnline){setSettingsLoading(false);return;}const tasks:Promise<void>[]=[];if(canNotifications)tasks.push(loadNotifications(organization.id,user.id).then(setNotifications),loadNotificationPreferences(organization.id,user.id).then(setPrefs));tasks.push(loadOrganizationSettings(organization.id).then((v)=>{const now=new Date().toISOString();applySettings(v);cacheOrganizationSettings(localStore,organization.id,v,now);setSettingsSyncedAt(now);setSettingsCached(false);}));if(canSub)tasks.push(loadSubscription(organization.id).then((v)=>{setSubscription(v.subscription);setPlan(v.plan);}));if(canAudit)tasks.push(loadAuditLogs(organization.id,branch?.id).then(setAudit));if(canImport)tasks.push(loadImportJobs(organization.id).then(setJobs));try{await Promise.all(tasks);}finally{setSettingsLoading(false);}};
 useEffect(()=>{const timer=setTimeout(()=>void refresh().catch((e)=>{setSettingsLoading(false);setError(e instanceof Error?e.message:String(e));}),0);return()=>clearTimeout(timer);},[organization?.id,branch?.id,user?.id,canSettings,canImport,canAudit,canNotifications,canSub,isOnline]);
 if(!organization||!user)return <SafeAreaView style={s.safe}><View style={s.center}><Text>{t('organization.noOrganization')}</Text></View></SafeAreaView>;
 const togglePref=async(key:'email'|'sms'|'whatsapp'|'push')=>{if(!mutationsAllowed)return;const base=prefs??{organization_id:organization.id,user_id:user.id,in_app:true,email:false,sms:false,whatsapp:false,push:false,updated_at:new Date().toISOString()};const next={...base,[key]:!base[key]};setPrefs(await saveNotificationPreferences({organization_id:next.organization_id,user_id:next.user_id,in_app:next.in_app,email:next.email,sms:next.sms,whatsapp:next.whatsapp,push:next.push}));};
 const saveSettings=async()=>{const threshold=Number(lowStock);if(!mutationsAllowed||!Number.isFinite(threshold)||threshold<0)return;setBusy(true);try{const saved=await saveOrganizationSettings({organization_id:organization.id,receipt_footer:receiptFooter||null,default_payment_method:defaultPayment,low_stock_default_threshold:threshold});const now=new Date().toISOString();setSettings(saved);cacheOrganizationSettings(localStore,organization.id,saved,now);setSettingsSyncedAt(now);setSettingsCached(false);setMessage(t('common.save'));}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
 const doStageImport=async()=>{if(!mutationsAllowed)return;const rows=parseCsv(csv);if(!rows.length)return;setBusy(true);try{await stageImport({organizationId:organization.id,branchId:branch?.id,type:importType,fileName,rows});setCsv('');setMessage(t('sprint7.admin.stage'));setJobs(await loadImportJobs(organization.id));}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
 const doCommitImport=async(id:string)=>{if(!mutationsAllowed)return;setBusy(true);setError(null);try{const count=await commitImportJob(id);setMessage(`${t('sprint7.admin.imports')}: ${count}`);setJobs(await loadImportJobs(organization.id));}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
 const markRead=async(id:string)=>{if(!mutationsAllowed)return;await markNotificationRead(id);await refresh();};
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.container}><View style={s.header}><View><Text style={s.title}>{t('sprint7.admin.title')}</Text><Text style={s.sub}>{t('sprint7.admin.subtitle')}</Text></View><Link href="/">{t('organization.back')}</Link></View>{error?<Text style={s.error}>{error}</Text>:null}{message?<Text style={s.success}>{message}</Text>:null}
 {canNotifications?<View style={s.card}><Text style={s.section}>{t('sprint7.admin.notifications')}</Text><View style={s.prefRow}>{(['email','sms','whatsapp','push'] as const).map(key=><View key={key} style={s.pref}><Text>{key.toUpperCase()}</Text><Switch disabled={!mutationsAllowed||busy} value={prefs?.[key]??false} onValueChange={()=>void togglePref(key)}/></View>)}</View>{!mutationsAllowed?<Text accessibilityRole="alert" style={s.meta}>{t(usingCachedData?'production.settings.freshAuthorizationRequired':'production.settings.onlineOnly')}</Text>:null}{notifications.length===0?<Text style={s.meta}>{t('sprint7.admin.noNotifications')}</Text>:notifications.map(n=><View key={n.id} style={s.row}><View style={{flex:1}}><Text style={s.bold}>{n.title_key}</Text><Text style={s.meta}>{n.body_key}</Text></View>{!n.read_at?<Pressable disabled={!mutationsAllowed||busy} onPress={()=>void markRead(n.id)}><Text style={[s.link,(!mutationsAllowed||busy)&&s.disabled]}>{t('sprint7.admin.markRead')}</Text></Pressable>:null}</View>)}</View>:null}
 {canSettings?<View style={s.card}><Text style={s.section}>{t('sprint7.admin.settings')}</Text><ReadModelStatus loading={settingsLoading} usingCachedData={settingsCached} stale={isSnapshotStale(settingsSyncedAt?{data:settings,syncedAt:settingsSyncedAt}:null,OPERATIONAL_READ_MODEL_MAX_AGE_MS)} syncedAt={settingsSyncedAt} hasData={settings!==null}/><TextInput accessibilityLabel={t('sprint7.admin.receiptFooter')} editable={mutationsAllowed&&!busy} style={s.input} value={receiptFooter} onChangeText={setReceiptFooter} placeholder={t('sprint7.admin.receiptFooter')}/><TextInput accessibilityLabel={t('sprint7.admin.lowStock')} editable={mutationsAllowed&&!busy} style={s.input} value={lowStock} onChangeText={setLowStock} keyboardType="decimal-pad" placeholder={t('sprint7.admin.lowStock')}/><View style={s.chips}>{(['CASH','CARD','MOBILE_MONEY','BANK_TRANSFER','OTHER'] as const).map(m=><Pressable accessibilityRole="button" disabled={!mutationsAllowed||busy} key={m} onPress={()=>setDefaultPayment(m)} style={[s.chip,defaultPayment===m&&s.chipActive,(!mutationsAllowed||busy)&&s.disabled]}><Text style={defaultPayment===m?s.chipTextActive:s.chipText}>{t(`production.settings.payment.${m}`)}</Text></Pressable>)}</View><Pressable accessibilityRole="button" disabled={busy||!mutationsAllowed} onPress={()=>void saveSettings()} style={[s.primary,(busy||!mutationsAllowed)&&s.disabled]}><Text style={s.primaryText}>{t('sprint7.admin.saveSettings')}</Text></Pressable>{!mutationsAllowed?<Text accessibilityRole="alert" style={s.meta}>{t(usingCachedData?'production.settings.freshAuthorizationRequired':'production.settings.onlineOnly')}</Text>:null}</View>:null}
 {canSub?<View style={s.card}><Text style={s.section}>{t('sprint7.admin.subscription')}</Text><Text style={s.bold}>{plan?.name??subscription?.plan_code??'CORE_35000'}</Text><Text style={s.meta}>{t('sprint7.admin.status')}: {subscription?.status??'NOT_ACTIVATED'}</Text><Text style={s.bold}>{Number(plan?.monthly_price??35000).toLocaleString()} {plan?.currency_code??'XOF'} / {t('sprint7.admin.monthly')}</Text></View>:null}
 {canImport?<View style={s.card}><Text style={s.section}>{t('sprint7.admin.imports')}</Text>{!mutationsAllowed?<Text accessibilityRole="alert" style={s.meta}>{t(usingCachedData?'production.settings.freshAuthorizationRequired':'production.settings.onlineOnly')}</Text>:null}<View style={s.chips}>{importTypes.map(v=><Pressable disabled={!mutationsAllowed||busy} key={v} onPress={()=>setImportType(v)} style={[s.chip,importType===v&&s.chipActive,(!mutationsAllowed||busy)&&s.disabled]}><Text style={importType===v?s.chipTextActive:s.chipText}>{v}</Text></Pressable>)}</View><TextInput editable={mutationsAllowed&&!busy} style={s.input} value={fileName} onChangeText={setFileName} placeholder={t('sprint7.admin.fileName')}/><TextInput editable={mutationsAllowed&&!busy} style={[s.input,{minHeight:120}]} multiline value={csv} onChangeText={setCsv} placeholder={`${t('sprint7.admin.csv')}\nname,phone,email`}/><Pressable disabled={busy||!mutationsAllowed||!csv.trim()} onPress={()=>void doStageImport()} style={[s.primary,(busy||!mutationsAllowed||!csv.trim())&&s.disabled]}><Text style={s.primaryText}>{t('sprint7.admin.stage')}</Text></Pressable><Text style={s.section}>{t('sprint7.admin.jobs')}</Text>{jobs.length===0?<Text style={s.meta}>{t('sprint7.admin.noJobs')}</Text>:jobs.map(j=><View key={j.id} style={s.row}><View><Text style={s.bold}>{j.import_type}</Text><Text style={s.meta}>{j.status} · {j.valid_rows}/{j.total_rows}</Text></View>{j.status==='READY'||j.status==='FAILED'?<Pressable disabled={busy||!mutationsAllowed} onPress={()=>void doCommitImport(j.id)} style={[s.secondary,(busy||!mutationsAllowed)&&s.disabled]}><Text>{t('sprint7.admin.stage')} ✓</Text></Pressable>:null}</View>)}</View>:null}
 {canAudit?<View style={s.card}><Text style={s.section}>{t('sprint7.admin.audit')}</Text>{audit.length===0?<Text style={s.meta}>{t('sprint7.admin.noAudit')}</Text>:audit.map(a=><View key={a.id} style={s.row}><View><Text style={s.bold}>{a.event_type}</Text><Text style={s.meta}>{a.entity_type??''} {a.entity_id??''}</Text></View><Text style={s.meta}>{new Date(a.created_at).toLocaleString()}</Text></View>)}</View>:null}
 </ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#F6F8FC'},container:{padding:24,gap:16,maxWidth:1000,width:'100%',alignSelf:'center'},center:{flex:1,alignItems:'center',justifyContent:'center',gap:12},header:{flexDirection:'row',flexWrap:'wrap',justifyContent:'space-between',gap:12},title:{fontSize:28,fontWeight:'800',color:'#102A5C'},sub:{color:'#667085',marginTop:4},card:{backgroundColor:'#fff',padding:18,borderRadius:16,gap:12},section:{fontSize:19,fontWeight:'700',color:'#102A5C'},input:{borderWidth:1,borderColor:'#D0D5DD',borderRadius:10,padding:12,minHeight:44},primary:{backgroundColor:'#102A5C',padding:12,borderRadius:10,alignSelf:'flex-start',minHeight:44,justifyContent:'center'},secondary:{borderWidth:1,borderColor:'#98A2B3',padding:8,borderRadius:8,minHeight:44,justifyContent:'center'},primaryText:{color:'#fff',fontWeight:'700'},row:{flexDirection:'row',flexWrap:'wrap',justifyContent:'space-between',gap:12,alignItems:'center',paddingVertical:10,borderBottomWidth:1,borderBottomColor:'#EAECF0'},bold:{fontWeight:'700',color:'#101828'},meta:{color:'#667085'},link:{color:'#102A5C',fontWeight:'700'},error:{color:'#B42318',fontWeight:'600'},success:{color:'#027A48',fontWeight:'600'},chips:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{borderWidth:1,borderColor:'#D0D5DD',borderRadius:999,paddingVertical:8,paddingHorizontal:12,minHeight:44,justifyContent:'center'},chipActive:{backgroundColor:'#102A5C',borderColor:'#102A5C'},chipText:{color:'#344054'},chipTextActive:{color:'#fff'},prefRow:{flexDirection:'row',flexWrap:'wrap',gap:14},pref:{flexDirection:'row',alignItems:'center',gap:6},disabled:{opacity:.45}});
