import { useEffect, useMemo, useState } from 'react';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Link } from 'expo-router';
import { useTranslation } from 'react-i18next';
import { useOrganization } from '@/providers/OrganizationProvider';
import { useConnectivity } from '@/providers/ConnectivityProvider';
import { loadCustomers, type Customer } from '@/services/coreCompletion';
import { loadInventoryBalances } from '@/services/inventory';
import { completeSale, loadSaleItems, loadSales, quoteSale, refundSale, searchPosProducts, type CartLine, type PosProduct, type Sale, type SaleItem } from '@/services/sales';
import { cacheSaleQuote, createOfflinePosStores, getCachedSaleQuote, queueOfflineSale, replayPendingSales } from '@/offline/offlinePos';
import { cachePosStockSnapshot, getCachedPosCatalog, getCachedPosStock, getOfflineAvailableQuantity, mergePosCatalog, searchCachedPosProducts, validateOfflineCartAgainstSnapshot } from '@/offline/offlinePosCatalog';

type CartRow = CartLine & { product: PosProduct };
const paymentMethods = ['CASH','CARD','MOBILE_MONEY','BANK_TRANSFER','OTHER'] as const;
const offlineStores = createOfflinePosStores();

export default function PosScreen() {
  const { t, i18n } = useTranslation();
  const { organization, branch, can } = useOrganization();
  const { isOnline } = useConnectivity();
  const organizationId=organization?.id; const branchId=branch?.id;
  const [query,setQuery]=useState(''); const [products,setProducts]=useState<PosProduct[]>([]); const [cart,setCart]=useState<CartRow[]>([]);
  const [catalogSyncedAt,setCatalogSyncedAt]=useState<string|null>(null); const [stockSyncedAt,setStockSyncedAt]=useState<string|null>(null);
  const [quoteTotal,setQuoteTotal]=useState(0); const [quoteSyncedAt,setQuoteSyncedAt]=useState<string|null>(null); const [paymentMethod,setPaymentMethod]=useState<(typeof paymentMethods)[number]>('CASH');
  const [customers,setCustomers]=useState<Customer[]>([]); const [selectedCustomerId,setSelectedCustomerId]=useState<string|null>(null);
  const [sales,setSales]=useState<Sale[]>([]); const [selectedSale,setSelectedSale]=useState<Sale|null>(null); const [saleItems,setSaleItems]=useState<SaleItem[]>([]);
  const [refundReason,setRefundReason]=useState(''); const [refundQuantity,setRefundQuantity]=useState('1'); const [busy,setBusy]=useState(false);
  const [pendingCount,setPendingCount]=useState(()=>offlineStores.outbox.pending().filter((item)=>item.kind==='SALE').length);
  const [conflictCount,setConflictCount]=useState(()=>offlineStores.outbox.conflicts().filter((item)=>item.kind==='SALE').length);
  const [error,setError]=useState<string|null>(null); const [message,setMessage]=useState<string|null>(null);
  const canCreate=can('sale.create'); const canRead=can('sale.read'); const canRefund=can('sale.refund'); const canReadCustomers=can('customer.read');
  const lines=useMemo(()=>cart.map(({product_id,quantity})=>({product_id,quantity})),[cart]);
  const displayTotal=lines.length?quoteTotal:0;
  const offlineText=i18n.language==='fr';

  const refreshOutboxState=()=>{setPendingCount(offlineStores.outbox.pending().filter((item)=>item.kind==='SALE').length);setConflictCount(offlineStores.outbox.conflicts().filter((item)=>item.kind==='SALE').length);};
  const refreshSales=async()=>{ if(!organizationId||!branchId||!canRead)return; setSales(await loadSales(organizationId,branchId)); };
  useEffect(()=>{ if(!organizationId||!branchId||!canRead||!isOnline)return; let active=true; void loadSales(organizationId,branchId).then((data)=>{if(active)setSales(data);}).catch((e)=>{if(active)setError(e.message);}); return()=>{active=false;}; },[organizationId,branchId,canRead,isOnline]);
  useEffect(()=>{ if(!organizationId||!canCreate)return; let active=true; const timer=setTimeout(()=>{if(!active)return;if(!isOnline){const cached=getCachedPosCatalog(offlineStores.localStore,organizationId);setCatalogSyncedAt(cached?.syncedAt??null);setProducts(searchCachedPosProducts(offlineStores.localStore,organizationId,query));return;}void searchPosProducts(organizationId,query).then((data)=>{if(active){const syncedAt=new Date().toISOString();mergePosCatalog(offlineStores.localStore,organizationId,data,syncedAt);setCatalogSyncedAt(syncedAt);setProducts(data);}}).catch((e)=>{if(active)setError(e.message);});},200); return()=>{active=false;clearTimeout(timer);}; },[organizationId,query,canCreate,isOnline]);
  useEffect(()=>{if(!organizationId||!branchId||!canCreate)return;let active=true;if(!isOnline){const cached=getCachedPosStock(offlineStores.localStore,organizationId,branchId);const timer=setTimeout(()=>{if(active)setStockSyncedAt(cached?.syncedAt??null);},0);return()=>{active=false;clearTimeout(timer);};}void loadInventoryBalances(organizationId,branchId).then((balances)=>{if(active){const syncedAt=new Date().toISOString();cachePosStockSnapshot(offlineStores.localStore,organizationId,branchId,balances,syncedAt);setStockSyncedAt(syncedAt);}}).catch((e)=>{if(active)setError(e.message);});return()=>{active=false;};},[organizationId,branchId,canCreate,isOnline]);
  useEffect(()=>{ let active=true; const timer=setTimeout(()=>{ if(!active)return; if(!organizationId||!branchId||!lines.length){setQuoteTotal(0);setQuoteSyncedAt(null);return;} if(!isOnline){const cached=getCachedSaleQuote(offlineStores.localStore,organizationId,branchId,lines);setQuoteTotal(cached?Number(cached.data.total_amount):0);setQuoteSyncedAt(cached?.syncedAt??null);if(!cached)setError(offlineText?'Aucun devis synchronisé pour ce panier. Connectez-vous avant de vendre hors ligne.':'No synchronized quote for this cart. Go online before selling it offline.');return;} void quoteSale(organizationId,branchId,lines).then((q)=>{if(active){const syncedAt=new Date().toISOString();cacheSaleQuote(offlineStores.localStore,organizationId,branchId,lines,q,syncedAt);setQuoteTotal(Number(q.total_amount));setQuoteSyncedAt(syncedAt);setError(null);}}).catch((e)=>{if(active){setQuoteTotal(0);setQuoteSyncedAt(null);setError(e.message);}}); },0); return()=>{active=false;clearTimeout(timer);}; },[organizationId,branchId,lines,isOnline,offlineText]);
  useEffect(()=>{if(!organizationId||!canReadCustomers||!isOnline)return;let active=true;void loadCustomers(organizationId).then((data)=>{if(active)setCustomers(data);}).catch((e)=>{if(active)setError(e.message);});return()=>{active=false;};},[organizationId,canReadCustomers,isOnline]);
  useEffect(()=>{if(!isOnline)return;let active=true;void replayPendingSales(offlineStores.outbox).then(async(result)=>{if(!active)return;refreshOutboxState();if(result.synced>0){setMessage(offlineText?`${result.synced} vente(s) hors ligne synchronisée(s).`:`${result.synced} offline sale(s) synchronized.`);await refreshSales();}if(result.conflicts>0)setError(offlineText?`${result.conflicts} vente(s) nécessitent une résolution de conflit.`:`${result.conflicts} sale(s) need conflict resolution.`);});return()=>{active=false;};},[isOnline,offlineText]);

  const offlineAvailable=(productId:string)=>organizationId&&branchId?getOfflineAvailableQuantity({store:offlineStores.localStore,outbox:offlineStores.outbox,organizationId,branchId,productId}):null;
  const addProduct=(product:PosProduct)=>{if(!isOnline){const available=offlineAvailable(product.id);const inCart=cart.find((row)=>row.product_id===product.id)?.quantity??0;if(available===null){setError(offlineText?'Aucun instantané de stock synchronisé. Reconnectez-vous avant de vendre hors ligne.':'No synchronized stock snapshot. Reconnect before selling offline.');return;}if(inCart+1>available){setError(offlineText?`Stock hors ligne disponible: ${available}`:`Offline available stock: ${available}`);return;}}setCart((current)=>{const existing=current.find((row)=>row.product_id===product.id); return existing?current.map((row)=>row.product_id===product.id?{...row,quantity:row.quantity+1}:row):[...current,{product_id:product.id,quantity:1,product}];});};
  const setQuantity=(productId:string,value:string)=>{const q=Number(value); if(!Number.isFinite(q)||q<=0)return;if(!isOnline){const available=offlineAvailable(productId);if(available===null||q>available){setError(offlineText?`Quantité supérieure au stock hors ligne disponible (${available??0}).`:`Quantity exceeds offline available stock (${available??0}).`);return;}}setCart((current)=>current.map((row)=>row.product_id===productId?{...row,quantity:q}:row));};
  const removeProduct=(productId:string)=>setCart((current)=>current.filter((row)=>row.product_id!==productId));

  const submitSale=async()=>{ if(!organizationId||!branchId||!lines.length||displayTotal<=0)return; setBusy(true);setError(null);setMessage(null); try{const stamp=Date.now(); const saleNumber=`SALE-${stamp}`; const idempotencyKey=`sale:${branchId}:${stamp}`; if(!isOnline){const stockCheck=validateOfflineCartAgainstSnapshot({store:offlineStores.localStore,outbox:offlineStores.outbox,organizationId,branchId,lines});if(!stockCheck.ok)throw new Error(stockCheck.reason==='NO_STOCK_SNAPSHOT'?(offlineText?'Aucun instantané de stock synchronisé.':'No synchronized stock snapshot.'):(offlineText?`Stock hors ligne insuffisant (${stockCheck.available}).`:`Insufficient offline stock (${stockCheck.available}).`));const cached=getCachedSaleQuote(offlineStores.localStore,organizationId,branchId,lines);if(!cached||!quoteSyncedAt)throw new Error(offlineText?'Cette vente ne peut pas être mise en attente hors ligne sans devis synchronisé.':'This sale cannot be queued offline without a synchronized quote.');queueOfflineSale({outbox:offlineStores.outbox,organizationId,branchId,saleNumber,lines,payments:[{method:paymentMethod,amount:displayTotal}],idempotencyKey,customerId:selectedCustomerId,quote:cached.data,quoteSyncedAt:cached.syncedAt});setCart([]);setSelectedCustomerId(null);refreshOutboxState();setMessage(offlineText?`Vente ${saleNumber} enregistrée · Synchronisation en attente`:`Sale ${saleNumber} saved · Pending sync`);return;} const saleId=await completeSale({organizationId,branchId,saleNumber,lines,payments:[{method:paymentMethod,amount:displayTotal}],idempotencyKey,customerId:selectedCustomerId}); setCart([]);setSelectedCustomerId(null);setMessage(`${t('pos.saleComplete')} · ${saleId.slice(0,8)}`); await refreshSales();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);} };
  const openSale=async(sale:Sale)=>{ if(!organizationId||!isOnline)return; setSelectedSale(sale); setSaleItems(await loadSaleItems(organizationId,sale.id)); };
  const submitRefund=async()=>{ const firstItem=saleItems[0]; if(!selectedSale||!firstItem||!refundReason.trim()||!isOnline)return; const qty=Number(refundQuantity); if(!Number.isFinite(qty)||qty<=0)return; setBusy(true);setError(null); try{const stamp=Date.now(); await refundSale({saleId:selectedSale.id,refundNumber:`REF-${stamp}`,items:[{sale_item_id:firstItem.id,quantity:qty}],idempotencyKey:`refund:${selectedSale.id}:${stamp}`,reason:refundReason}); setMessage(t('pos.refund')); setSelectedSale(null);setSaleItems([]);setRefundReason('');await refreshSales();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);} };

  if(!organization||!branch)return <SafeAreaView style={styles.safe}><View style={styles.center}><Text>{t('organization.noOrganization')}</Text></View></SafeAreaView>;
  if(!canRead&&!canCreate)return <SafeAreaView style={styles.safe}><View style={styles.center}><Text>{t('pos.cannotRead')}</Text><Link href="/">{t('organization.back')}</Link></View></SafeAreaView>;

  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.container}>
    <View style={styles.header}><View><Text style={styles.title}>{t('pos.title')}</Text><Text style={styles.subtitle}>{t('pos.subtitle')}</Text></View><Link href="/" style={styles.link}>{t('organization.back')}</Link></View>
    <View style={[styles.syncCard,!isOnline&&styles.offlineCard]}><Text style={styles.bold}>{isOnline?(offlineText?'En ligne · serveur disponible':'Online · server available'):(offlineText?'Hors ligne · catalogue et stock synchronisés utilisés':'Offline · using synchronized catalog and stock')}</Text><Text style={styles.meta}>{pendingCount} {offlineText?'en attente':'pending'} · {conflictCount} {offlineText?'conflit(s)':'conflict(s)'}</Text>{!isOnline?<Text style={styles.note}>{offlineText?`Catalogue: ${catalogSyncedAt?new Date(catalogSyncedAt).toLocaleString():'indisponible'} · Stock: ${stockSyncedAt?new Date(stockSyncedAt).toLocaleString():'indisponible'}`:`Catalog: ${catalogSyncedAt?new Date(catalogSyncedAt).toLocaleString():'unavailable'} · Stock: ${stockSyncedAt?new Date(stockSyncedAt).toLocaleString():'unavailable'}`}</Text>:null}</View>
    {error?<Text style={styles.error}>{error}</Text>:null}{message?<Text style={styles.success}>{message}</Text>:null}
    {canCreate?<><View style={styles.card}><TextInput value={query} onChangeText={setQuery} placeholder={t('pos.search')} style={styles.input}/>{!isOnline?<Text style={styles.note}>{offlineText?'Recherche dans le dernier catalogue synchronisé. Les données peuvent être obsolètes.':'Searching the last synchronized catalog. Data may be stale.'}</Text>:null}<View style={styles.list}>{products.map((p)=><View key={p.id} style={styles.row}><View style={styles.flex}><Text style={styles.bold}>{p.name}</Text><Text style={styles.meta}>{p.generic_name||p.brand_name||p.sku||''}{!isOnline&&offlineAvailable(p.id)!==null?` · ${offlineAvailable(p.id)} ${offlineText?'disponible hors ligne':'offline available'}`:''}</Text></View><Pressable style={styles.button} onPress={()=>addProduct(p)}><Text style={styles.buttonText}>{t('pos.add')}</Text></Pressable></View>)}</View></View>
    <View style={styles.card}><Text style={styles.section}>{t('pos.cart')}</Text>{cart.length===0?<Text style={styles.meta}>{t('pos.emptyCart')}</Text>:cart.map((row)=><View key={row.product_id} style={styles.row}><View style={styles.flex}><Text style={styles.bold}>{row.product.name}</Text><Text style={styles.meta}>{t('pos.quantity')}{!isOnline&&offlineAvailable(row.product_id)!==null?` · ${offlineAvailable(row.product_id)} ${offlineText?'restant':'remaining'}`:''}</Text></View><TextInput keyboardType="decimal-pad" value={String(row.quantity)} onChangeText={(v)=>setQuantity(row.product_id,v)} style={styles.qty}/><Pressable onPress={()=>removeProduct(row.product_id)}><Text style={styles.remove}>×</Text></Pressable></View>)}<Text style={styles.total}>{t('pos.estimatedTotal')}: {displayTotal.toLocaleString()} XOF</Text><Text style={styles.note}>{isOnline?t('pos.serverPriceNote'):(quoteSyncedAt?(offlineText?`Prix basé sur le dernier devis serveur synchronisé à ${new Date(quoteSyncedAt).toLocaleTimeString()}. Le serveur revalidera la vente.`:`Price based on the last server quote synchronized at ${new Date(quoteSyncedAt).toLocaleTimeString()}. The server will revalidate the sale.`):(offlineText?'Aucun prix hors ligne fiable pour ce panier.':'No trusted offline price for this cart.'))}</Text></View>
    <View style={styles.card}><Text style={styles.section}>{t('pos.payment')}</Text>{canReadCustomers&&isOnline?<><Text style={styles.meta}>{t('sprint7.customers.title')}</Text><View style={styles.chips}><Pressable onPress={()=>setSelectedCustomerId(null)} style={[styles.chip,selectedCustomerId===null&&styles.chipActive]}><Text style={selectedCustomerId===null?styles.chipTextActive:styles.chipText}>{t('common.noData')}</Text></Pressable>{customers.slice(0,20).map(c=><Pressable key={c.id} onPress={()=>setSelectedCustomerId(c.id)} style={[styles.chip,selectedCustomerId===c.id&&styles.chipActive]}><Text style={selectedCustomerId===c.id?styles.chipTextActive:styles.chipText}>{c.full_name}</Text></Pressable>)}</View></>:null}<View style={styles.chips}>{paymentMethods.map((m)=><Pressable key={m} onPress={()=>setPaymentMethod(m)} style={[styles.chip,paymentMethod===m&&styles.chipActive]}><Text style={paymentMethod===m?styles.chipTextActive:styles.chipText}>{m==='CASH'?t('pos.cash'):m==='CARD'?t('pos.card'):m==='MOBILE_MONEY'?t('pos.mobileMoney'):m==='BANK_TRANSFER'?t('pos.bankTransfer'):t('pos.other')}</Text></Pressable>)}</View><Pressable disabled={busy||!cart.length||displayTotal<=0} onPress={()=>void submitSale()} style={[styles.primary,(busy||!cart.length||displayTotal<=0)&&styles.disabled]}><Text style={styles.buttonText}>{busy?t('common.loading'):(isOnline?t('pos.completeSale'):(offlineText?'Enregistrer · Synchronisation en attente':'Save · Pending sync'))}</Text></Pressable></View></>:null}
    {canRead?<View style={styles.card}><Text style={styles.section}>{t('pos.salesHistory')}</Text>{!isOnline?<Text style={styles.note}>{offlineText?'Historique serveur indisponible hors ligne. Les ventes en attente sont indiquées ci-dessus.':'Server history is unavailable offline. Pending sales are shown above.'}</Text>:sales.length===0?<Text style={styles.meta}>{t('pos.noSales')}</Text>:sales.map((sale)=><Pressable key={sale.id} style={styles.saleRow} onPress={()=>void openSale(sale)}><View><Text style={styles.bold}>{sale.sale_number}</Text><Text style={styles.meta}>{new Date(sale.completed_at).toLocaleString()} · {sale.status}</Text></View><Text style={styles.bold}>{Number(sale.total_amount).toLocaleString()} {sale.currency_code}</Text></Pressable>)}</View>:null}
    {selectedSale?<View style={styles.card}><Text style={styles.section}>{t('pos.receipt')} · {selectedSale.sale_number}</Text>{saleItems.map((item)=><Text key={item.id} style={styles.meta}>{item.quantity} × {Number(item.unit_price).toLocaleString()} = {Number(item.line_total).toLocaleString()} XOF</Text>)}<Text style={styles.total}>{Number(selectedSale.total_amount).toLocaleString()} {selectedSale.currency_code}</Text>{canRefund&&selectedSale.status!=='REFUNDED'?<><TextInput value={refundReason} onChangeText={setRefundReason} placeholder={t('pos.refundReason')} style={styles.input}/><TextInput value={refundQuantity} onChangeText={setRefundQuantity} keyboardType="decimal-pad" placeholder={t('pos.refundQuantity')} style={styles.input}/><Pressable disabled={busy||!refundReason.trim()||!isOnline} onPress={()=>void submitRefund()} style={styles.secondary}><Text>{t('pos.confirmRefund')}</Text></Pressable></>:null}</View>:null}
  </ScrollView></SafeAreaView>;
}

const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F6F8FC'},container:{padding:24,gap:16,maxWidth:1000,width:'100%',alignSelf:'center'},center:{flex:1,alignItems:'center',justifyContent:'center',gap:12},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start',gap:12},title:{fontSize:28,fontWeight:'800',color:'#102A5C'},subtitle:{fontSize:15,color:'#667085',marginTop:4},link:{color:'#102A5C',fontWeight:'700'},card:{backgroundColor:'#fff',padding:18,borderRadius:16,gap:12},syncCard:{backgroundColor:'#ECFDF3',padding:14,borderRadius:12,gap:4},offlineCard:{backgroundColor:'#FFF7ED'},section:{fontSize:19,fontWeight:'700',color:'#102A5C'},input:{borderWidth:1,borderColor:'#D0D5DD',borderRadius:10,padding:12},list:{gap:8},row:{flexDirection:'row',alignItems:'center',gap:10,paddingVertical:8,borderBottomWidth:1,borderBottomColor:'#EAECF0'},saleRow:{flexDirection:'row',justifyContent:'space-between',gap:12,paddingVertical:12,borderBottomWidth:1,borderBottomColor:'#EAECF0'},flex:{flex:1},bold:{fontWeight:'700',color:'#101828'},meta:{color:'#667085'},button:{backgroundColor:'#102A5C',paddingVertical:8,paddingHorizontal:12,borderRadius:8},primary:{backgroundColor:'#102A5C',padding:14,borderRadius:10,alignItems:'center'},secondary:{borderWidth:1,borderColor:'#98A2B3',padding:12,borderRadius:10,alignItems:'center'},buttonText:{color:'#fff',fontWeight:'700'},qty:{width:72,borderWidth:1,borderColor:'#D0D5DD',borderRadius:8,padding:8,textAlign:'center'},remove:{fontSize:26,color:'#B42318'},total:{fontSize:18,fontWeight:'800',color:'#102A5C'},note:{fontSize:12,color:'#667085'},chips:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{borderWidth:1,borderColor:'#D0D5DD',borderRadius:999,paddingVertical:8,paddingHorizontal:12},chipActive:{backgroundColor:'#102A5C',borderColor:'#102A5C'},chipText:{color:'#344054'},chipTextActive:{color:'#fff'},error:{color:'#B42318',fontWeight:'600'},success:{color:'#027A48',fontWeight:'600'},disabled:{opacity:.5}});
