import { useEffect, useMemo, useState } from 'react';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Link } from 'expo-router';
import { useTranslation } from 'react-i18next';
import { useOrganization } from '@/providers/OrganizationProvider';
import { useConnectivity } from '@/providers/ConnectivityProvider';
import { loadCustomers, type Customer } from '@/services/coreCompletion';
import { loadInventoryBalances } from '@/services/inventory';
import { completeSale, loadSaleItems, loadSales, quoteSale, refundSale, searchPosProducts, type CartLine, type PosProduct, type Sale, type SaleItem } from '@/services/sales';
import { cacheSaleQuote, createOfflinePosStores, getCachedSaleQuote, queueOfflineSale, replayPendingSales } from '@/offline/offlinePos';
import { cachePosStockSnapshot, getCachedPosCatalog, getCachedPosStock, getOfflineAvailableQuantity, mergePosCatalog, searchCachedPosProducts, validateOfflineCartAgainstSnapshot } from '@/offline/offlinePosCatalog';
import { formatPosCurrency, formatPosDate, posStatusTranslationKey } from '@/utils/posPresentation';

type CartRow = CartLine & { product: PosProduct };
const paymentMethods = ['CASH', 'CARD', 'MOBILE_MONEY', 'BANK_TRANSFER', 'OTHER'] as const;
const offlineStores = createOfflinePosStores();

export default function PosScreen() {
  const { t, i18n } = useTranslation();
  const { organization, branch, can } = useOrganization();
  const { isOnline } = useConnectivity();
  const organizationId = organization?.id;
  const branchId = branch?.id;
  const language = i18n.language === 'fr' ? 'fr' : 'en';
  const [query, setQuery] = useState(''); const [products, setProducts] = useState<PosProduct[]>([]); const [cart, setCart] = useState<CartRow[]>([]);
  const [catalogSyncedAt, setCatalogSyncedAt] = useState<string | null>(null); const [stockSyncedAt, setStockSyncedAt] = useState<string | null>(null);
  const [quoteTotal, setQuoteTotal] = useState(0); const [quoteSyncedAt, setQuoteSyncedAt] = useState<string | null>(null); const [paymentMethod, setPaymentMethod] = useState<(typeof paymentMethods)[number]>('CASH');
  const [customers, setCustomers] = useState<Customer[]>([]); const [selectedCustomerId, setSelectedCustomerId] = useState<string | null>(null);
  const [sales, setSales] = useState<Sale[]>([]); const [selectedSale, setSelectedSale] = useState<Sale | null>(null); const [saleItems, setSaleItems] = useState<SaleItem[]>([]);
  const [refundReason, setRefundReason] = useState(''); const [refundQuantity, setRefundQuantity] = useState('1'); const [busy, setBusy] = useState(false);
  const [pendingCount, setPendingCount] = useState(() => offlineStores.outbox.pending().filter((item) => item.kind === 'SALE').length); const [conflictCount, setConflictCount] = useState(() => offlineStores.outbox.conflicts().filter((item) => item.kind === 'SALE').length);
  const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null);
  const canCreate = can('sale.create'); const canRead = can('sale.read'); const canRefund = can('sale.refund'); const canReadCustomers = can('customer.read');
  const lines = useMemo(() => cart.map(({ product_id, quantity }) => ({ product_id, quantity })), [cart]); const displayTotal = lines.length ? quoteTotal : 0; const currencyCode = organization?.currency_code ?? 'XOF';
  const refreshOutboxState = () => { setPendingCount(offlineStores.outbox.pending().filter((item) => item.kind === 'SALE').length); setConflictCount(offlineStores.outbox.conflicts().filter((item) => item.kind === 'SALE').length); };
  const refreshSales = async () => { if (organizationId && branchId && canRead) setSales(await loadSales(organizationId, branchId)); };

  useEffect(() => { if (!organizationId || !branchId || !canRead || !isOnline) return; let active = true; void loadSales(organizationId, branchId).then((data) => active && setSales(data)).catch((cause) => active && setError(cause.message)); return () => { active = false; }; }, [organizationId, branchId, canRead, isOnline]);
  useEffect(() => { if (!organizationId || !canCreate) return; let active = true; const timer = setTimeout(() => { if (!active) return; if (!isOnline) { const cached = getCachedPosCatalog(offlineStores.localStore, organizationId); setCatalogSyncedAt(cached?.syncedAt ?? null); setProducts(searchCachedPosProducts(offlineStores.localStore, organizationId, query)); return; } void searchPosProducts(organizationId, query).then((data) => { if (!active) return; const syncedAt = new Date().toISOString(); mergePosCatalog(offlineStores.localStore, organizationId, data, syncedAt); setCatalogSyncedAt(syncedAt); setProducts(data); }).catch((cause) => active && setError(cause.message)); }, 200); return () => { active = false; clearTimeout(timer); }; }, [organizationId, query, canCreate, isOnline]);
  useEffect(() => { if (!organizationId || !branchId || !canCreate) return; let active = true; if (!isOnline) { const cached = getCachedPosStock(offlineStores.localStore, organizationId, branchId); const timer = setTimeout(() => active && setStockSyncedAt(cached?.syncedAt ?? null), 0); return () => { active = false; clearTimeout(timer); }; } void loadInventoryBalances(organizationId, branchId).then((balances) => { if (!active) return; const syncedAt = new Date().toISOString(); cachePosStockSnapshot(offlineStores.localStore, organizationId, branchId, balances, syncedAt); setStockSyncedAt(syncedAt); }).catch((cause) => active && setError(cause.message)); return () => { active = false; }; }, [organizationId, branchId, canCreate, isOnline]);
  useEffect(() => { let active = true; const timer = setTimeout(() => { if (!active) return; if (!organizationId || !branchId || !lines.length) { setQuoteTotal(0); setQuoteSyncedAt(null); return; } if (!isOnline) { const cached = getCachedSaleQuote(offlineStores.localStore, organizationId, branchId, lines); setQuoteTotal(cached ? Number(cached.data.total_amount) : 0); setQuoteSyncedAt(cached?.syncedAt ?? null); if (!cached) setError(t('pos.noTrustedOfflinePrice')); return; } void quoteSale(organizationId, branchId, lines).then((quote) => { if (!active) return; const syncedAt = new Date().toISOString(); cacheSaleQuote(offlineStores.localStore, organizationId, branchId, lines, quote, syncedAt); setQuoteTotal(Number(quote.total_amount)); setQuoteSyncedAt(syncedAt); setError(null); }).catch((cause) => active && (setQuoteTotal(0), setQuoteSyncedAt(null), setError(cause.message))); }, 0); return () => { active = false; clearTimeout(timer); }; }, [organizationId, branchId, lines, isOnline, t]);
  useEffect(() => { if (!organizationId || !canReadCustomers || !isOnline) return; let active = true; void loadCustomers(organizationId).then((data) => active && setCustomers(data)).catch((cause) => active && setError(cause.message)); return () => { active = false; }; }, [organizationId, canReadCustomers, isOnline]);
  useEffect(() => { if (!isOnline) return; let active = true; void replayPendingSales(offlineStores.outbox).then(async (result) => { if (!active) return; refreshOutboxState(); if (result.synced > 0) { setMessage(t('pos.offlineSalesSynchronized', { count: result.synced })); await refreshSales(); } if (result.conflicts > 0) setError(t('pos.offlineSalesConflict', { count: result.conflicts })); }); return () => { active = false; }; }, [isOnline, t]);

  const offlineAvailable = (productId: string) => organizationId && branchId ? getOfflineAvailableQuantity({ store: offlineStores.localStore, outbox: offlineStores.outbox, organizationId, branchId, productId }) : null;
  const addProduct = (product: PosProduct) => { if (!isOnline) { const available = offlineAvailable(product.id); const inCart = cart.find((row) => row.product_id === product.id)?.quantity ?? 0; if (available === null) { setError(t('pos.noOfflineStockSnapshot')); return; } if (inCart + 1 > available) { setError(t('pos.offlineStockAvailable', { count: available })); return; } } setCart((current) => { const existing = current.find((row) => row.product_id === product.id); return existing ? current.map((row) => row.product_id === product.id ? { ...row, quantity: row.quantity + 1 } : row) : [...current, { product_id: product.id, quantity: 1, product }]; }); };
  const setQuantity = (productId: string, value: string) => { const quantity = Number(value); if (!Number.isFinite(quantity) || quantity <= 0) return; if (!isOnline) { const available = offlineAvailable(productId); if (available === null || quantity > available) { setError(t('pos.offlineQuantityExceeded', { count: available ?? 0 })); return; } } setCart((current) => current.map((row) => row.product_id === productId ? { ...row, quantity } : row)); };
  const removeProduct = (productId: string) => setCart((current) => current.filter((row) => row.product_id !== productId));
  const submitSale = async () => { if (!organizationId || !branchId || !lines.length || displayTotal <= 0) return; setBusy(true); setError(null); setMessage(null); try { const stamp = Date.now(); const saleNumber = `SALE-${stamp}`; const idempotencyKey = `sale:${branchId}:${stamp}`; if (!isOnline) { const stockCheck = validateOfflineCartAgainstSnapshot({ store: offlineStores.localStore, outbox: offlineStores.outbox, organizationId, branchId, lines }); if (!stockCheck.ok) throw new Error(stockCheck.reason === 'NO_STOCK_SNAPSHOT' ? t('pos.noOfflineStockSnapshot') : t('pos.insufficientStock')); const cached = getCachedSaleQuote(offlineStores.localStore, organizationId, branchId, lines); if (!cached || !quoteSyncedAt) throw new Error(t('pos.offlineQuoteRequired')); queueOfflineSale({ outbox: offlineStores.outbox, organizationId, branchId, saleNumber, lines, payments: [{ method: paymentMethod, amount: displayTotal }], idempotencyKey, customerId: selectedCustomerId, quote: cached.data, quoteSyncedAt: cached.syncedAt }); setCart([]); setSelectedCustomerId(null); refreshOutboxState(); setMessage(t('pos.saleSavedPending', { saleNumber })); return; } const saleId = await completeSale({ organizationId, branchId, saleNumber, lines, payments: [{ method: paymentMethod, amount: displayTotal }], idempotencyKey, customerId: selectedCustomerId }); setCart([]); setSelectedCustomerId(null); setMessage(`${t('pos.saleComplete')} · ${saleId.slice(0, 8)}`); await refreshSales(); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } finally { setBusy(false); } };
  const openSale = async (sale: Sale) => { if (organizationId && isOnline) { setSelectedSale(sale); setSaleItems(await loadSaleItems(organizationId, sale.id)); } };
  const submitRefund = async () => { const firstItem = saleItems[0]; const quantity = Number(refundQuantity); if (!selectedSale || !firstItem || !refundReason.trim() || !isOnline || !Number.isFinite(quantity) || quantity <= 0) return; setBusy(true); setError(null); try { const stamp = Date.now(); await refundSale({ saleId: selectedSale.id, refundNumber: `REF-${stamp}`, items: [{ sale_item_id: firstItem.id, quantity }], idempotencyKey: `refund:${selectedSale.id}:${stamp}`, reason: refundReason }); setMessage(t('pos.refund')); setSelectedSale(null); setSaleItems([]); setRefundReason(''); await refreshSales(); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } finally { setBusy(false); } };

  if (!organization || !branch) return <SafeAreaView style={styles.safe}><View style={styles.center}><Text>{t('organization.noOrganization')}</Text></View></SafeAreaView>;
  if (!canRead && !canCreate) return <SafeAreaView style={styles.safe}><View style={styles.center}><Text>{t('pos.cannotRead')}</Text><Link href="/">{t('organization.back')}</Link></View></SafeAreaView>;
  const timestamp = (value: string | null) => value ? formatPosDate(value, language) : t('pos.unavailable');
  const paymentLabel = (method: typeof paymentMethods[number]) => t(`pos.${method === 'CASH' ? 'cash' : method === 'CARD' ? 'card' : method === 'MOBILE_MONEY' ? 'mobileMoney' : method === 'BANK_TRANSFER' ? 'bankTransfer' : 'other'}`);
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.container} keyboardShouldPersistTaps="handled">
    <View style={styles.header}><View><Text accessibilityRole="header" style={styles.title}>{t('pos.title')}</Text><Text style={styles.subtitle}>{t('pos.subtitle')}</Text></View><Link href="/" asChild><Pressable accessibilityRole="button" style={styles.backButton}><Text style={styles.backText}>{t('organization.back')}</Text></Pressable></Link></View>
    <View accessibilityRole="summary" style={[styles.syncCard, !isOnline && styles.offlineCard]}><Text style={styles.bold}>{isOnline ? t('pos.online') : t('pos.offline')}</Text><Text style={styles.meta}>{t('pos.pendingCount', { count: pendingCount })} · {t('pos.conflictCount', { count: conflictCount })}</Text>{!isOnline ? <Text style={styles.note}>{t('pos.catalogSynced', { timestamp: timestamp(catalogSyncedAt), stockTimestamp: timestamp(stockSyncedAt) })}</Text> : null}</View>
    {error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}{message ? <Text accessibilityRole="alert" style={styles.success}>{message}</Text> : null}
    {canCreate ? <><View style={styles.card}><Text accessibilityRole="header" style={styles.section}>{t('pos.search')}</Text><TextInput accessibilityLabel={t('pos.search')} value={query} onChangeText={setQuery} placeholder={t('pos.search')} style={styles.input}/>{!isOnline ? <Text style={styles.note}>{t('pos.searchingCached')}</Text> : null}<View style={styles.list}>{products.map((product) => <View key={product.id} style={styles.row}><View style={styles.flex}><Text style={styles.bold}>{product.name}</Text><Text style={styles.meta}>{product.generic_name || product.brand_name || product.sku || ''}{!isOnline && offlineAvailable(product.id) !== null ? ` · ${t('pos.offlineAvailable', { count: offlineAvailable(product.id) })}` : ''}</Text></View><Pressable accessibilityRole="button" accessibilityLabel={`${t('pos.add')} ${product.name}`} style={styles.button} onPress={() => addProduct(product)}><Text style={styles.buttonText}>{t('pos.add')}</Text></Pressable></View>)}</View></View>
    <View style={styles.card}><Text accessibilityRole="header" style={styles.section}>{t('pos.cart')}</Text>{cart.length === 0 ? <Text style={styles.meta}>{t('pos.emptyCart')}</Text> : cart.map((row) => <View key={row.product_id} style={styles.row}><View style={styles.flex}><Text style={styles.bold}>{row.product.name}</Text><Text style={styles.meta}>{t('pos.quantity')}{!isOnline && offlineAvailable(row.product_id) !== null ? ` · ${t('pos.remaining', { count: offlineAvailable(row.product_id) })}` : ''}</Text></View><TextInput accessibilityLabel={`${t('pos.quantity')} ${row.product.name}`} keyboardType="decimal-pad" value={String(row.quantity)} onChangeText={(value) => setQuantity(row.product_id, value)} style={styles.qty}/><Pressable accessibilityRole="button" accessibilityLabel={t('pos.removeItem', { name: row.product.name })} onPress={() => removeProduct(row.product_id)} style={styles.iconButton}><Text style={styles.remove}>×</Text></Pressable></View>)}<Text style={styles.total}>{t('pos.estimatedTotal')}: {formatPosCurrency(displayTotal, currencyCode, language)}</Text><Text style={styles.note}>{isOnline ? t('pos.serverPriceNote') : quoteSyncedAt ? t('pos.offlinePriceQuote', { timestamp: formatPosDate(quoteSyncedAt, language) }) : t('pos.noTrustedOfflinePrice')}</Text></View>
    <View style={styles.card}><Text accessibilityRole="header" style={styles.section}>{t('pos.payment')}</Text>{canReadCustomers && isOnline ? <><Text style={styles.meta}>{t('sprint7.customers.title')}</Text><View accessibilityRole="tablist" style={styles.chips}><Pressable accessibilityRole="tab" accessibilityState={{ selected: selectedCustomerId === null }} onPress={() => setSelectedCustomerId(null)} style={[styles.chip, selectedCustomerId === null && styles.chipActive]}><Text style={selectedCustomerId === null ? styles.chipTextActive : styles.chipText}>{t('pos.noCustomer')}</Text></Pressable>{customers.slice(0, 20).map((customer) => <Pressable accessibilityRole="tab" accessibilityState={{ selected: selectedCustomerId === customer.id }} accessibilityLabel={t('pos.selectCustomer', { name: customer.full_name })} key={customer.id} onPress={() => setSelectedCustomerId(customer.id)} style={[styles.chip, selectedCustomerId === customer.id && styles.chipActive]}><Text style={selectedCustomerId === customer.id ? styles.chipTextActive : styles.chipText}>{customer.full_name}</Text></Pressable>)}</View></> : null}<Text style={styles.meta}>{t('pos.paymentMethod')}</Text><View accessibilityRole="tablist" style={styles.chips}>{paymentMethods.map((method) => <Pressable accessibilityRole="tab" accessibilityState={{ selected: paymentMethod === method }} accessibilityLabel={t('pos.selectPayment', { method: paymentLabel(method) })} key={method} onPress={() => setPaymentMethod(method)} style={[styles.chip, paymentMethod === method && styles.chipActive]}><Text style={paymentMethod === method ? styles.chipTextActive : styles.chipText}>{paymentLabel(method)}</Text></Pressable>)}</View><Pressable accessibilityRole="button" disabled={busy || !cart.length || displayTotal <= 0} onPress={() => void submitSale()} style={[styles.primary, (busy || !cart.length || displayTotal <= 0) && styles.disabled]}><Text style={styles.buttonText}>{busy ? t('common.loading') : isOnline ? t('pos.completeSale') : t('pos.savePendingSync')}</Text></Pressable></View></> : null}
    {canRead ? <View style={styles.card}><Text accessibilityRole="header" style={styles.section}>{t('pos.salesHistory')}</Text>{!isOnline ? <Text style={styles.note}>{t('pos.offlineHistoryUnavailable')}</Text> : sales.length === 0 ? <Text style={styles.meta}>{t('pos.noSales')}</Text> : sales.map((sale) => <Pressable accessibilityRole="button" accessibilityLabel={t('pos.openReceipt', { saleNumber: sale.sale_number })} key={sale.id} style={styles.saleRow} onPress={() => void openSale(sale)}><View><Text style={styles.bold}>{sale.sale_number}</Text><Text style={styles.meta}>{formatPosDate(sale.completed_at, language)} · {t(posStatusTranslationKey(sale.status))}</Text></View><Text style={styles.bold}>{formatPosCurrency(Number(sale.total_amount), sale.currency_code, language)}</Text></Pressable>)}</View> : null}
    {selectedSale ? <View style={styles.card}><View style={styles.receiptHeader}><Text accessibilityRole="header" style={styles.section}>{t('pos.receipt')} · {selectedSale.sale_number}</Text><Pressable accessibilityRole="button" accessibilityLabel={t('pos.closeReceipt')} onPress={() => { setSelectedSale(null); setSaleItems([]); }} style={styles.iconButton}><Text style={styles.remove}>×</Text></Pressable></View>{saleItems.map((item) => <Text key={item.id} style={styles.meta}>{item.quantity} × {formatPosCurrency(Number(item.unit_price), selectedSale.currency_code, language)} = {formatPosCurrency(Number(item.line_total), selectedSale.currency_code, language)}</Text>)}<Text style={styles.total}>{formatPosCurrency(Number(selectedSale.total_amount), selectedSale.currency_code, language)}</Text>{canRefund && selectedSale.status !== 'REFUNDED' ? <><TextInput accessibilityLabel={t('pos.refundReason')} value={refundReason} onChangeText={setRefundReason} placeholder={t('pos.refundReason')} style={styles.input}/><TextInput accessibilityLabel={t('pos.refundQuantity')} value={refundQuantity} onChangeText={setRefundQuantity} keyboardType="decimal-pad" placeholder={t('pos.refundQuantity')} style={styles.input}/><Pressable accessibilityRole="button" disabled={busy || !refundReason.trim() || !isOnline} onPress={() => void submitRefund()} style={[styles.secondary, (busy || !refundReason.trim() || !isOnline) && styles.disabled]}><Text style={styles.secondaryText}>{t('pos.confirmRefund')}</Text></Pressable></> : null}</View> : null}
  </ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#F6F8FC' }, container: { padding: 24, gap: 16, maxWidth: 1000, width: '100%', alignSelf: 'center' }, center: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 12 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: 12 }, title: { fontSize: 28, fontWeight: '800', color: '#102A5C' }, subtitle: { fontSize: 15, color: '#667085', marginTop: 4 }, backButton: { minHeight: 44, justifyContent: 'center', paddingHorizontal: 12 }, backText: { color: '#102A5C', fontWeight: '700' }, card: { backgroundColor: '#fff', padding: 18, borderRadius: 16, gap: 12 }, syncCard: { backgroundColor: '#ECFDF3', padding: 14, borderRadius: 12, gap: 4 }, offlineCard: { backgroundColor: '#FFF7ED' }, section: { fontSize: 19, fontWeight: '700', color: '#102A5C' }, input: { minHeight: 44, borderWidth: 1, borderColor: '#D0D5DD', borderRadius: 10, paddingHorizontal: 12, color: '#101828' }, list: { gap: 8 }, row: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: '#EAECF0' }, saleRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 12, paddingVertical: 12, minHeight: 56, borderBottomWidth: 1, borderBottomColor: '#EAECF0' }, flex: { flex: 1 }, bold: { fontWeight: '700', color: '#101828' }, meta: { color: '#667085' }, button: { minHeight: 44, backgroundColor: '#102A5C', justifyContent: 'center', paddingHorizontal: 14, borderRadius: 8 }, primary: { minHeight: 48, backgroundColor: '#102A5C', justifyContent: 'center', paddingHorizontal: 16, borderRadius: 10, alignItems: 'center' }, secondary: { minHeight: 44, borderWidth: 1, borderColor: '#98A2B3', justifyContent: 'center', paddingHorizontal: 14, borderRadius: 10, alignItems: 'center', alignSelf: 'flex-start' }, buttonText: { color: '#fff', fontWeight: '700' }, secondaryText: { color: '#344054', fontWeight: '700' }, qty: { width: 72, minHeight: 44, borderWidth: 1, borderColor: '#D0D5DD', borderRadius: 8, paddingHorizontal: 8, textAlign: 'center', color: '#101828' }, iconButton: { minWidth: 44, minHeight: 44, justifyContent: 'center', alignItems: 'center' }, remove: { fontSize: 26, color: '#B42318' }, total: { fontSize: 18, fontWeight: '800', color: '#102A5C' }, note: { fontSize: 12, color: '#667085' }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, chip: { minHeight: 44, borderWidth: 1, borderColor: '#D0D5DD', borderRadius: 999, paddingVertical: 8, paddingHorizontal: 12, justifyContent: 'center' }, chipActive: { backgroundColor: '#102A5C', borderColor: '#102A5C' }, chipText: { color: '#344054' }, chipTextActive: { color: '#fff' }, error: { color: '#B42318', fontWeight: '600' }, success: { color: '#027A48', fontWeight: '600' }, disabled: { opacity: .5 }, receiptHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12 },
});
