import { useEffect, useState } from 'react';
import { Link } from 'expo-router';
import { SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useTranslation } from 'react-i18next';
import { useOrganization } from '@/providers/OrganizationProvider';
import { loadDailySales, loadInventoryValue, type DailySalesReport, type InventoryValueReport } from '@/services/coreCompletion';

export default function ReportsScreen(){
 const{t}=useTranslation();const{organization,branch,can}=useOrganization();const[sales,setSales]=useState<DailySalesReport[]>([]);const[stock,setStock]=useState<InventoryValueReport|null>(null);const[error,setError]=useState<string|null>(null);const canRead=can('reports.read');
 useEffect(()=>{if(!organization||!branch||!canRead)return;void Promise.all([loadDailySales(organization.id,branch.id),loadInventoryValue(organization.id,branch.id)]).then(([a,b])=>{setSales(a);setStock(b);}).catch((e)=>setError(e instanceof Error?e.message:String(e)));},[organization,branch,canRead]);
 if(!organization||!branch)return <SafeAreaView style={s.safe}><View style={s.center}><Text>{t('organization.noOrganization')}</Text></View></SafeAreaView>;
 if(!canRead)return <SafeAreaView style={s.safe}><View style={s.center}><Text>{t('sprint7.reports.cannotRead')}</Text><Link href="/">{t('organization.back')}</Link></View></SafeAreaView>;
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.container}><View style={s.header}><View><Text style={s.title}>{t('sprint7.reports.title')}</Text><Text style={s.sub}>{t('sprint7.reports.subtitle')}</Text></View><Link href="/">{t('organization.back')}</Link></View>{error?<Text style={s.error}>{error}</Text>:null}
 <View style={s.card}><Text style={s.section}>{t('sprint7.reports.inventoryValue')}</Text>{stock?<View style={s.metrics}><Metric label={t('sprint7.reports.stockedBatches')} value={String(stock.stocked_batches??0)}/><Metric label={t('sprint7.reports.costValue')} value={`${Number(stock.inventory_cost_value??0).toLocaleString()} XOF`}/><Metric label={t('sprint7.reports.retailValue')} value={`${Number(stock.inventory_retail_value??0).toLocaleString()} XOF`}/></View>:<Text style={s.meta}>{t('sprint7.reports.noData')}</Text>}</View>
 <View style={s.card}><Text style={s.section}>{t('sprint7.reports.dailySales')}</Text>{sales.length===0?<Text style={s.meta}>{t('sprint7.reports.noData')}</Text>:sales.map(row=><View key={row.sale_date??Math.random()} style={s.row}><Text style={s.bold}>{row.sale_date}</Text><Text style={s.meta}>{t('sprint7.reports.saleCount')}: {row.sale_count??0}</Text><Text style={s.bold}>{Number(row.gross_sales??0).toLocaleString()} XOF</Text></View>)}</View></ScrollView></SafeAreaView>;
}
function Metric({label,value}:{label:string;value:string}){return <View style={s.metric}><Text style={s.meta}>{label}</Text><Text style={s.metricValue}>{value}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#F6F8FC'},container:{padding:24,gap:16,maxWidth:1000,width:'100%',alignSelf:'center'},center:{flex:1,alignItems:'center',justifyContent:'center',gap:12},header:{flexDirection:'row',justifyContent:'space-between',gap:12},title:{fontSize:28,fontWeight:'800',color:'#102A5C'},sub:{color:'#667085',marginTop:4},card:{backgroundColor:'#fff',padding:18,borderRadius:16,gap:12},section:{fontSize:19,fontWeight:'700',color:'#102A5C'},metrics:{flexDirection:'row',flexWrap:'wrap',gap:12},metric:{minWidth:180,borderWidth:1,borderColor:'#EAECF0',borderRadius:12,padding:14,gap:4},metricValue:{fontSize:20,fontWeight:'800',color:'#102A5C'},row:{flexDirection:'row',justifyContent:'space-between',gap:12,paddingVertical:10,borderBottomWidth:1,borderBottomColor:'#EAECF0'},bold:{fontWeight:'700',color:'#101828'},meta:{color:'#667085'},error:{color:'#B42318',fontWeight:'600'}});
