import { useEffect, useMemo, useState } from 'react';
import { Link } from 'expo-router';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useTranslation } from 'react-i18next';
import { ReadModelStatus } from '@/components/ReadModelStatus';
import { useConnectivity } from '@/providers/ConnectivityProvider';
import { useOrganization } from '@/providers/OrganizationProvider';
import { canApplyTransferAction, validateReceivedQuantity } from '@/domain/transferSafety';
import { LocalStore } from '@/offline/localStore';
import { cacheTransferLines, cacheTransfersReadModel, getCachedTransferLines, getCachedTransfersReadModel } from '@/offline/expiryTransfersReadModels';
import { isSnapshotStale, OPERATIONAL_READ_MODEL_MAX_AGE_MS } from '@/offline/readModels';
import { approveStockTransfer, cancelStockTransfer, createStockTransfer, dispatchStockTransfer, loadTransferableBatches, loadTransferLines, loadTransfers, receiveStockTransfer, type StockTransfer, type StockTransferLine, type TransferBatch } from '@/services/transfers';

type DraftLine={source_batch_id:string;quantity:number};
const localStore=new LocalStore();
export default function TransfersScreen(){
 const{t}=useTranslation();const{isOnline}=useConnectivity();const{organization,branches,branch,can,usingCachedData:usingCachedPermissions}=useOrganization();
 const[transfers,setTransfers]=useState<StockTransfer[]>([]);const[batches,setBatches]=useState<TransferBatch[]>([]);const[destination,setDestination]=useState('');const[draft,setDraft]=useState<DraftLine[]>([]);const[notes,setNotes]=useState('');const[selected,setSelected]=useState<StockTransfer|null>(null);const[lines,setLines]=useState<StockTransferLine[]>([]);const[received,setReceived]=useState<Record<string,string>>({});const[reasons,setReasons]=useState<Record<string,string>>({});const[discrepancyNotes,setDiscrepancyNotes]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[message,setMessage]=useState<string|null>(null);
 const[loading,setLoading]=useState(false);const[syncedAt,setSyncedAt]=useState<string|null>(null);const[usingCachedData,setUsingCachedData]=useState(false);
 const canRead=can('transfer.read');const canCreate=can('transfer.create');const canApprove=can('transfer.approve');const canDispatch=can('transfer.dispatch');const canReceive=can('transfer.receive');
 const destinations=useMemo(()=>branches.filter(b=>b.id!==branch?.id),[branches,branch?.id]);
 const effectiveDestination=destination||destinations[0]?.id||'';
 const mutationAllowed=isOnline&&!usingCachedPermissions;
 const refresh=async()=>{if(!organization||!branch||!canRead||!isOnline)return;const transferRows=await loadTransfers(organization.id);const batchRows=canCreate?await loadTransferableBatches(organization.id,branch.id):[];setTransfers(transferRows);setBatches(batchRows);cacheTransfersReadModel(localStore,organization.id,branch.id,{transfers:transferRows,transferableBatches:batchRows});setSyncedAt(new Date().toISOString());setUsingCachedData(false);};
 useEffect(()=>{
  if(!organization||!branch||!canRead)return;
  let active=true;
  const load=async()=>{
   const cached=getCachedTransfersReadModel(localStore,organization.id,branch.id);
   if(cached){setTransfers(cached.data.transfers);setBatches(cached.data.transferableBatches);setSyncedAt(cached.syncedAt);setUsingCachedData(true);}
   if(!isOnline){if(!cached)setError(t('production.readModel.noCachedData'));return;}
   setLoading(true);setError(null);
   const transferRows=await loadTransfers(organization.id);
   const batchRows=branch&&canCreate?await loadTransferableBatches(organization.id,branch.id):[];
   if(!active)return;
   setTransfers(transferRows);
   setBatches(batchRows);
   cacheTransfersReadModel(localStore,organization.id,branch.id,{transfers:transferRows,transferableBatches:batchRows});
   setSyncedAt(new Date().toISOString());setUsingCachedData(false);setLoading(false);
  };
  void load().catch(e=>{if(active){setError(e instanceof Error?e.message:String(e));setLoading(false);}});
  return()=>{active=false;};
 },[organization,branch,canRead,canCreate,isOnline,t]);
 if(!organization||!branch)return <SafeAreaView style={s.safe}><View style={s.center}><Text>{t('organization.noOrganization')}</Text></View></SafeAreaView>;
 if(!canRead)return <SafeAreaView style={s.safe}><View style={s.center}><Text>{t('sprint8.transfers.permissionDenied')}</Text><Link href="/">{t('organization.back')}</Link></View></SafeAreaView>;
 const addLine=(b:TransferBatch)=>setDraft(cur=>cur.some(x=>x.source_batch_id===b.id)?cur:[...cur,{source_batch_id:b.id,quantity:1}]);
 const setQty=(id:string,v:string)=>{const q=Number(v);if(Number.isFinite(q)&&q>0)setDraft(cur=>cur.map(x=>x.source_batch_id===id?{...x,quantity:q}:x));};
 const submit=async()=>{if(!mutationAllowed||!effectiveDestination||!draft.length)return;setBusy(true);setError(null);try{const stamp=Date.now();await createStockTransfer({organizationId:organization.id,sourceBranchId:branch.id,destinationBranchId:effectiveDestination,transferNumber:`TR-${stamp}`,lines:draft,idempotencyKey:`transfer:${organization.id}:${stamp}`,notes});setDraft([]);setNotes('');setMessage(t('sprint8.transfers.requestSuccess'));await refresh();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
 const open=async(tr:StockTransfer)=>{setSelected(tr);const cached=getCachedTransferLines(localStore,organization.id,tr.id);if(cached){setLines(cached.data);setReceived(Object.fromEntries(cached.data.map(l=>[l.id,String(l.dispatched_quantity)])));}if(!isOnline){if(!cached)setError(t('production.readModel.noCachedData'));return;}const ls=await loadTransferLines(organization.id,tr.id);cacheTransferLines(localStore,organization.id,tr.id,ls);setLines(ls);setReceived(Object.fromEntries(ls.map(l=>[l.id,String(l.dispatched_quantity)])));};
 const act=async(kind:'approve'|'dispatch'|'cancel')=>{if(!selected||!mutationAllowed||!canApplyTransferAction(selected.status,kind))return;setBusy(true);setError(null);try{if(kind==='approve')await approveStockTransfer(selected.id);if(kind==='dispatch')await dispatchStockTransfer(selected.id);if(kind==='cancel')await cancelStockTransfer(selected.id);setMessage(t('sprint8.transfers.actionSuccess'));setSelected(null);await refresh();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
 const receive=async()=>{if(!selected||!mutationAllowed||!canApplyTransferAction(selected.status,'receive'))return;const receivedLines=lines.map(l=>({line_id:l.id,quantity:Number(received[l.id]??l.dispatched_quantity),reason:reasons[l.id],dispatched:l.dispatched_quantity}));if(receivedLines.some(line=>!validateReceivedQuantity(line.quantity,line.dispatched))){setError('INVALID_RECEIVED_QUANTITY');return;}setBusy(true);setError(null);try{await receiveStockTransfer(selected.id,receivedLines.map(({line_id,quantity,reason})=>({line_id,quantity,reason})),discrepancyNotes);setMessage(t('sprint8.transfers.actionSuccess'));setSelected(null);setDiscrepancyNotes('');await refresh();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
 const statusLabel=(v:StockTransfer['status'])=>v==='REQUESTED'?t('sprint8.transfers.requested'):v==='APPROVED'?t('sprint8.transfers.approved'):v==='DISPATCHED'?t('sprint8.transfers.dispatched'):v==='RECEIVED'?t('sprint8.transfers.received'):v==='RECEIVED_WITH_DISCREPANCY'?t('sprint8.transfers.discrepancy'):t('sprint8.transfers.cancelled');
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.container}>
  <View style={s.header}><View><Text style={s.title}>{t('sprint8.transfers.title')}</Text><Text style={s.meta}>{t('sprint8.transfers.subtitle')}</Text></View><Link href="/">{t('organization.back')}</Link></View><ReadModelStatus loading={loading} usingCachedData={usingCachedData} stale={isSnapshotStale(syncedAt?{data:null,syncedAt}:null,OPERATIONAL_READ_MODEL_MAX_AGE_MS)} syncedAt={syncedAt} hasData={transfers.length+batches.length>0}/>{!mutationAllowed?<Text accessibilityRole="alert" style={s.error}>{t('production.inventoryView.offlineReadOnly')}</Text>:null}{error?<Text style={s.error}>{error}</Text>:null}{message?<Text style={s.success}>{message}</Text>:null}
  {canCreate?<View style={s.card}><Text style={s.section}>{t('sprint8.transfers.new')}</Text><Text style={s.bold}>{t('sprint8.transfers.source')}: {branch.name}</Text><Text style={s.label}>{t('sprint8.transfers.destination')}</Text><View style={s.chips}>{destinations.map(b=><Pressable key={b.id} onPress={()=>setDestination(b.id)} style={[s.chip,effectiveDestination===b.id&&s.chipActive]}><Text style={effectiveDestination===b.id?s.chipTextActive:s.chipText}>{b.name}</Text></Pressable>)}</View>{destinations.length===0?<Text style={s.meta}>{t('sprint8.transfers.selectDestination')}</Text>:null}<Text style={s.label}>{t('sprint8.transfers.batch')}</Text>{batches.length===0?<Text style={s.meta}>{t('sprint8.transfers.noBatches')}</Text>:batches.map(b=><View key={b.id} style={s.row}><View style={s.flex}><Text style={s.bold}>{b.product?.name}</Text><Text style={s.meta}>{t('sprint8.transfers.lot')}: {b.lot_number} · {t('sprint8.transfers.expiry')}: {b.expiry_date} · {t('sprint8.transfers.available')}: {b.balance}</Text></View><Pressable onPress={()=>addLine(b)} style={s.secondary}><Text>{t('sprint8.transfers.addLine')}</Text></Pressable></View>)}{draft.map(d=>{const b=batches.find(x=>x.id===d.source_batch_id);return <View key={d.source_batch_id} style={s.row}><Text style={s.flex}>{b?.product?.name} · {b?.lot_number}</Text><TextInput style={s.qty} keyboardType="decimal-pad" value={String(d.quantity)} onChangeText={v=>setQty(d.source_batch_id,v)}/><Pressable onPress={()=>setDraft(cur=>cur.filter(x=>x.source_batch_id!==d.source_batch_id))}><Text style={s.remove}>×</Text></Pressable></View>})}<TextInput style={s.input} value={notes} onChangeText={setNotes} placeholder={t('sprint8.transfers.notes')}/><Pressable disabled={busy||!effectiveDestination||!draft.length} onPress={()=>void submit()} style={[s.primary,(busy||!effectiveDestination||!draft.length)&&s.disabled]}><Text style={s.primaryText}>{t('sprint8.transfers.create')}</Text></Pressable></View>:null}
  <View style={s.card}><Text style={s.section}>{t('sprint8.transfers.history')}</Text>{transfers.length===0?<Text style={s.meta}>{t('sprint8.transfers.noTransfers')}</Text>:transfers.map(tr=><Pressable key={tr.id} onPress={()=>void open(tr)} style={s.row}><View style={s.flex}><Text style={s.bold}>{tr.transfer_number}</Text><Text style={s.meta}>{statusLabel(tr.status)} · {new Date(tr.created_at).toLocaleString()}</Text></View><Text style={s.link}>{t('sprint8.transfers.details')}</Text></Pressable>)}</View>
  {selected?<View style={s.card}><Text style={s.section}>{selected.transfer_number}</Text><Text style={s.bold}>{t('sprint8.transfers.status')}: {statusLabel(selected.status)}</Text>{lines.map(l=><View key={l.id} style={s.lineBox}><Text style={s.meta}>{l.requested_quantity} requested · {l.dispatched_quantity} dispatched · {l.received_quantity} received</Text>{selected.status==='DISPATCHED'&&canReceive?<><TextInput style={s.input} keyboardType="decimal-pad" value={received[l.id]??''} onChangeText={v=>setReceived(r=>({...r,[l.id]:v}))} placeholder={t('sprint8.transfers.receivedQty')}/><TextInput style={s.input} value={reasons[l.id]??''} onChangeText={v=>setReasons(r=>({...r,[l.id]:v}))} placeholder={t('sprint8.transfers.discrepancyReason')}/></>:null}</View>)}<View style={s.actions}>{selected.status==='REQUESTED'&&canApprove?<Pressable onPress={()=>void act('approve')} style={s.primary}><Text style={s.primaryText}>{t('sprint8.transfers.approve')}</Text></Pressable>:null}{selected.status==='APPROVED'&&canDispatch?<Pressable onPress={()=>void act('dispatch')} style={s.primary}><Text style={s.primaryText}>{t('sprint8.transfers.dispatch')}</Text></Pressable>:null}{['REQUESTED','APPROVED'].includes(selected.status)&&canCreate?<Pressable onPress={()=>void act('cancel')} style={s.secondary}><Text>{t('sprint8.transfers.cancel')}</Text></Pressable>:null}</View>{selected.status==='DISPATCHED'&&canReceive?<><TextInput style={s.input} value={discrepancyNotes} onChangeText={setDiscrepancyNotes} placeholder={t('sprint8.transfers.discrepancyNotes')}/><Pressable onPress={()=>void receive()} style={s.primary}><Text style={s.primaryText}>{t('sprint8.transfers.confirmReceive')}</Text></Pressable></>:null}</View>:null}
 </ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#F6F8FC'},container:{padding:24,gap:16,maxWidth:1000,width:'100%',alignSelf:'center'},center:{flex:1,alignItems:'center',justifyContent:'center',gap:12},header:{flexDirection:'row',justifyContent:'space-between',gap:12},title:{fontSize:28,fontWeight:'800',color:'#102A5C'},section:{fontSize:19,fontWeight:'700',color:'#102A5C'},card:{backgroundColor:'#fff',padding:18,borderRadius:16,gap:12},row:{flexDirection:'row',alignItems:'center',gap:10,paddingVertical:9,borderBottomWidth:1,borderBottomColor:'#EAECF0'},flex:{flex:1},bold:{fontWeight:'700',color:'#101828'},meta:{color:'#667085'},label:{fontWeight:'700',color:'#344054'},input:{borderWidth:1,borderColor:'#D0D5DD',borderRadius:10,padding:11},qty:{width:76,borderWidth:1,borderColor:'#D0D5DD',borderRadius:8,padding:8,textAlign:'center'},primary:{backgroundColor:'#102A5C',paddingVertical:11,paddingHorizontal:15,borderRadius:9,alignSelf:'flex-start'},primaryText:{color:'#fff',fontWeight:'700'},secondary:{borderWidth:1,borderColor:'#98A2B3',paddingVertical:8,paddingHorizontal:12,borderRadius:9},disabled:{opacity:.45},chips:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{borderWidth:1,borderColor:'#D0D5DD',borderRadius:999,paddingVertical:8,paddingHorizontal:12},chipActive:{backgroundColor:'#102A5C',borderColor:'#102A5C'},chipText:{color:'#344054'},chipTextActive:{color:'#fff'},remove:{fontSize:24,color:'#B42318'},link:{color:'#102A5C',fontWeight:'700'},error:{color:'#B42318',fontWeight:'600'},success:{color:'#027A48',fontWeight:'600'},actions:{flexDirection:'row',flexWrap:'wrap',gap:8},lineBox:{gap:8,paddingVertical:8}});
